services:
  web:
    image: kriszoza/react-sws-1
    container_name: react
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  caddy:
    external: true