name: Deploy React CSR
on:
  push:
    branches:
      - main
      - features/**
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Print Foo variables
        run: echo "dev:\ ${{ vars.FOO }}"
      - name: Print API Key
        run: echo "Api Key:\ ${{ secrets.API_KEY }}"
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Caching
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install deps
        run: npm i
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: Force fail
        run: exit 1

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."

  notify-success:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: https://discordapp.com/api/webhooks/1421349019224903712/GDlAsXm361j7yJLu8cXpD0xRCmHVTCJZKS6zids7AxYvpPk-htSuUTM4iMtmb7-ReiQI
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Success ✅ - ${{ github.ref_name }}@${{ github.sha }} by ${{ github.actor }}'

  notify-failed:
    if: failure()
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: https://discordapp.com/api/webhooks/1421349019224903712/GDlAsXm361j7yJLu8cXpD0xRCmHVTCJZKS6zids7AxYvpPk-htSuUTM4iMtmb7-ReiQI
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Failed ⚠️ - ${{ github.ref_name }}@${{ github.sha }} by ${{ github.actor }}'
