name: Deploy React CSR to Surge
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install and Cache
        uses: ./.github/actions/install-cache
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        uses: ./.github/actions/deploy-surge
        with:
          token: ${{ secrets.SURGE_TOKEN }}
          email: ${{ secrets.SURGE_EMAIL }}
          dist-folder: dist
          domain: ${{ vars.SURGE_DOMAIN }} 

  notify-success:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Success ✅ - ${{ github.ref_name }}@${{ github.sha }} by ${{ github.actor }}'

  notify-failed:
    if: failure()
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - name: Notify to Discord Text Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build Failed ⚠️ - ${{ github.ref_name }}@${{ github.sha }} by ${{ github.actor }}'
