name: Deploy React CSR
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install deps
        run: npm i
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."